[package]
name = "Word_guessing_game"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
clearscreen = "2.0.1"
rand = "0.8.5"
serde = "1.0.203"
serde_derive = "1.0.203"
unicode-normalization = "0.1.23"
